import type { HeroStat, IndustryRow, Scenario, ScenarioId } from './types';

export const heroStats: HeroStat[] = [
  { value: '22%', label: 'Of the annual rate gap covered at the stated investment objective' },
  { value: '$443M/yr', label: 'Remaining structural gap at objective returns (before repricing)' },
  { value: '~4.4 years', label: 'Estimated buffer runway at objective-return conditions' },
  { value: '~6.5% nominal', label: 'Approximate annual return required to avoid reserve erosion' },
];

export const industryRows: IndustryRow[] = [
  {
    name: 'Other Sectors (aggregate)',
    baseRate: 1.55,
    riskFactor: 1.1806,
    costRate: 1.83,
    payrollB: 144.64,
    exposureM: 405,
    currentPremiumM: 2242,
    costPremiumM: 2647,
    perEmployeeImpact: 211,
    employment: 1_920_000,
    frequencyIndex: 1,
    severityIndex: 1,
    wageIndex: 1,
  },
  {
    name: 'General Construction',
    baseRate: 2.75,
    riskFactor: 1.1806,
    costRate: 3.25,
    payrollB: 18.52,
    exposureM: 92.6,
    currentPremiumM: 508.8,
    costPremiumM: 601.4,
    perEmployeeImpact: 370,
    employment: 250_000,
    frequencyIndex: 1.47,
    severityIndex: 1.33,
    wageIndex: 1.12,
  },
  {
    name: 'Local Government',
    baseRate: 3.71,
    riskFactor: 1.1806,
    costRate: 4.38,
    payrollB: 7,
    exposureM: 46.9,
    currentPremiumM: 259.7,
    costPremiumM: 306.6,
    perEmployeeImpact: 580,
    employment: 81_000,
    frequencyIndex: 1.25,
    severityIndex: 1.2,
    wageIndex: 1.1,
  },
  {
    name: 'Retail & Wholesale',
    baseRate: 1.5,
    riskFactor: 1.1806,
    costRate: 1.77,
    payrollB: 10,
    exposureM: 27,
    currentPremiumM: 150,
    costPremiumM: 177,
    perEmployeeImpact: 135,
    employment: 200_000,
    frequencyIndex: 0.97,
    severityIndex: 0.91,
    wageIndex: 0.95,
  },
  {
    name: 'Manufacturing',
    baseRate: 2,
    riskFactor: 1.1806,
    costRate: 2.36,
    payrollB: 7,
    exposureM: 25.2,
    currentPremiumM: 140,
    costPremiumM: 165.2,
    perEmployeeImpact: 240,
    employment: 105_000,
    frequencyIndex: 1.18,
    severityIndex: 1.12,
    wageIndex: 1.05,
  },
  {
    name: 'Community Health',
    baseRate: 3,
    riskFactor: 1.1806,
    costRate: 3.54,
    payrollB: 3.8,
    exposureM: 20.5,
    currentPremiumM: 114,
    costPremiumM: 134.5,
    perEmployeeImpact: 410,
    employment: 50_000,
    frequencyIndex: 1.31,
    severityIndex: 1.22,
    wageIndex: 1.02,
  },
  {
    name: 'Schools (Public)',
    baseRate: 1.71,
    riskFactor: 1.1806,
    costRate: 2.02,
    payrollB: 5.48,
    exposureM: 17,
    currentPremiumM: 94.1,
    costPremiumM: 111.1,
    perEmployeeImpact: 210,
    employment: 75_000,
    frequencyIndex: 0.92,
    severityIndex: 0.94,
    wageIndex: 1.03,
  },
  {
    name: 'Courier/Warehousing',
    baseRate: 2.5,
    riskFactor: 1.1806,
    costRate: 2.95,
    payrollB: 3.2,
    exposureM: 14.4,
    currentPremiumM: 80,
    costPremiumM: 94.4,
    perEmployeeImpact: 360,
    employment: 50_000,
    frequencyIndex: 1.27,
    severityIndex: 1.09,
    wageIndex: 0.98,
  },
  {
    name: 'Long-Term Care',
    baseRate: 4.6,
    riskFactor: 1.1806,
    costRate: 5.43,
    payrollB: 1.7,
    exposureM: 14.1,
    currentPremiumM: 78.2,
    costPremiumM: 92.3,
    perEmployeeImpact: 500,
    employment: 28_000,
    frequencyIndex: 1.42,
    severityIndex: 1.28,
    wageIndex: 1.04,
  },
  {
    name: 'Utilities & Public Works',
    baseRate: 2.75,
    riskFactor: 1.1806,
    costRate: 3.25,
    payrollB: 2,
    exposureM: 10,
    currentPremiumM: 55,
    costPremiumM: 65,
    perEmployeeImpact: 500,
    employment: 30_000,
    frequencyIndex: 1.14,
    severityIndex: 1.17,
    wageIndex: 1.18,
  },
  {
    name: 'General Trucking',
    baseRate: 2.83,
    riskFactor: 1.1806,
    costRate: 3.34,
    payrollB: 1.76,
    exposureM: 9,
    currentPremiumM: 49.8,
    costPremiumM: 58.8,
    perEmployeeImpact: 450,
    employment: 25_000,
    frequencyIndex: 1.34,
    severityIndex: 1.24,
    wageIndex: 1.01,
  },
  {
    name: 'Restaurants & Taverns',
    baseRate: 0.58,
    riskFactor: 1.1806,
    costRate: 0.68,
    payrollB: 5.8,
    exposureM: 5.8,
    currentPremiumM: 33.6,
    costPremiumM: 39.4,
    perEmployeeImpact: 30,
    employment: 195_000,
    frequencyIndex: 0.82,
    severityIndex: 0.73,
    wageIndex: 0.79,
  },
];

export const scenarios: Record<ScenarioId, Scenario> = {
  A: {
    title: 'Discount-Rate Case (3.0% real)',
    trigger: 'Funding-basis returns track liability discount assumptions (~6.0% nominal) and do not close the rate gap',
    timeline: '~3.4 years buffer runway',
    annualIncrease: 'High urgency (full $570M annual draw)',
    totalShock: 'Fast normalization pressure',
    likelihood: 'Plausible within normal market cycles',
    fundedProgression: '140.8% → 138% → 135% → 132% → 130%',
    floor: 1.83,
    steps: [
      { year: 0, low: 1.55, high: 1.55 },
      { year: 1, low: 1.72, high: 1.78 },
      { year: 2, low: 1.83, high: 1.9 },
      { year: 3, low: 1.92, high: 2.0 },
    ],
  },
  B: {
    title: 'Objective Case (3.5% real)',
    trigger: 'Returns meet SIPG objective (~6.5% nominal), covering only ~22% of the annual suppression gap',
    timeline: '~4.4 years buffer runway',
    annualIncrease: 'Gradual but persistent normalization',
    totalShock: 'Moderate repricing path',
    likelihood: 'Planning baseline',
    fundedProgression: '140.8% → 139% → 137% → 135% → 133% → 130%',
    floor: 1.83,
    steps: [
      { year: 0, low: 1.55, high: 1.55 },
      { year: 2, low: 1.68, high: 1.74 },
      { year: 3, low: 1.76, high: 1.84 },
      { year: 4, low: 1.83, high: 1.92 },
      { year: 5, low: 1.9, high: 2.0 },
    ],
  },
  C: {
    title: 'Recent-Actual Case (2024: 6.8%)',
    trigger: 'Returns resemble 2024 funding-basis performance; draw slows but does not fully stop',
    timeline: '~6.7 years outer-bound runway',
    annualIncrease: 'Slow-burn normalization pressure',
    totalShock: 'Deferred, not eliminated',
    likelihood: 'Possible, but not a policy objective',
    fundedProgression: '140.8% → 139.5% → 138% → 136% → 134% → 132%',
    note: 'Even in a strong year, reserve draw was observed; repricing pressure may still accumulate over time.',
    floor: 1.83,
    steps: [
      { year: 0, low: 1.55, high: 1.55 },
      { year: 3, low: 1.62, high: 1.68 },
      { year: 4, low: 1.7, high: 1.78 },
      { year: 5, low: 1.78, high: 1.87 },
    ],
  },
  D: {
    title: 'Breakeven Case (~5.38% nominal requirement)',
    trigger: 'Investment income fully offsets the premium-to-cost gap; reserve erosion pauses',
    timeline: 'Indefinite only if sustained annually',
    annualIncrease: 'Minimal in the model',
    totalShock: 'No structural draw in steady state',
    likelihood: 'Low confidence as a long-run constant outcome',
    note: 'Any shortfall below breakeven reintroduces draw and accelerates normalization pressure.',
    fundedProgression: '140.8% → 140.8% (flat, conditional)',
    floor: 1.83,
    steps: [
      { year: 0, low: 1.55, high: 1.55 },
      { year: 4, low: 1.56, high: 1.62 },
      { year: 5, low: 1.58, high: 1.65 },
    ],
  },
};
