import { useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { CashFlowRow } from '@/lib/model/types';

export default function SparklineCashflow({ rows }: { rows: CashFlowRow[] }) {
  const [open, setOpen] = useState(false);
  return <><button type="button" onClick={() => setOpen(true)} className="h-48 w-full rounded-lg border bg-white p-4 text-left"><div className="mb-2 flex items-center justify-between"><p className="font-semibold text-[#003366]">Cash flow preview</p><span className="text-xs text-slate-500">Click to expand 25-year table</span></div><ResponsiveContainer width="100%" height="78%"><LineChart data={rows}><XAxis dataKey="calendarYear" hide /><YAxis hide /><Tooltip formatter={(v) => typeof v === 'number' ? `$${v.toFixed(0)}M` : v} /><Line type="monotone" dataKey="atfcf" dot={false} stroke="#003366" strokeWidth={2} /></LineChart></ResponsiveContainer></button><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-slate-950/30" /><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[80vh] w-[92vw] max-w-5xl -translate-x-1/2 -translate-y-1/2 overflow-auto rounded-xl bg-white p-6 shadow-2xl"><Dialog.Title className="text-xl font-bold text-[#003366]">Annual after-tax free cash flow</Dialog.Title><table className="mt-4 min-w-full text-sm"><thead><tr className="bg-slate-100 text-left"><th className="p-2">Year</th><th className="p-2">Revenue</th><th className="p-2">Royalty</th><th className="p-2">Prov. CIT</th><th className="p-2">ATFCF</th></tr></thead><tbody>{rows.map((row) => <tr key={row.year} className="border-t"><td className="p-2">{row.calendarYear}</td><td className="p-2">${row.revenue.toFixed(0)}M</td><td className="p-2">${row.royaltyAmount.toFixed(0)}M</td><td className="p-2">${row.citProvincial.toFixed(0)}M</td><td className="p-2">${row.atfcf.toFixed(0)}M</td></tr>)}</tbody></table><Dialog.Close className="mt-4 rounded bg-[#003366] px-4 py-2 text-white">Close</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
