import { useMemo, useRef, useState } from 'react';
import type { FocusEvent, FormEvent, ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';

const links:Record<string,string>={'01-home.md':'/','02-what-we-do.md':'/what-we-do/','03-fiscal-impact-growth-modelling.md':'/what-we-do/fiscal-impact-growth-modelling/','04-official-community-plan-policy-analysis.md':'/what-we-do/official-community-plan-policy-analysis/','05-economic-development-strategy.md':'/what-we-do/economic-development-strategy/','06-labour-market-analysis.md':'/what-we-do/labour-market-analysis/','07-resource-sector-complex-planning-analysis.md':'/what-we-do/resource-sector-complex-planning-analysis/','08-long-range-financial-scenario-planning.md':'/what-we-do/long-range-financial-scenario-planning/','09-public-interest-research-evidence-packages.md':'/what-we-do/public-interest-research-evidence-packages/','10-who-we-are.md':'/who-we-are/','11-insights.md':'/insights/','12-insight-housing-target-delivery.md':'/insights/when-a-housing-target-outruns-delivery/','13-insight-trade-gap-workforce-number.md':'/insights/the-trade-gap-hidden-inside-a-workforce-number/','14-insight-what-a-flag-tells-you.md':'/insights/what-a-flag-tells-you/','15-selected-work.md':'/selected-work/','16-contact.md':'/contact/','17-privacy.md':'/privacy/','18-legal.md':'/legal/','19-terms.md':'/terms/','20-accessibility.md':'/accessibility/'};
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function inline(s:string):ReactNode[]{ const out:ReactNode[]=[]; const re=/(\*\*([^*]+)\*\*|\[([^\]]+)\]\(\.\/([^)]+)\))/g; let last=0,m; while((m=re.exec(s))){out.push(s.slice(last,m.index)); if(m[2])out.push(<strong key={m.index}>{m[2]}</strong>);else out.push(<Link key={m.index} to={links[m[4]]||'/'}>{m[3]} <ArrowRight aria-hidden="true"/></Link>);last=re.lastIndex}out.push(s.slice(last));return out }
export function Markdown({source}:{source:string;path:string}){const blocks=useMemo(()=>{const lines=source.trim().split('\n'), result:ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue}if(line.startsWith('|')){const rows:string[][]=[];while(i<lines.length&&lines[i].trim().startsWith('|')){if(!/^\|[\s:|-]+\|$/.test(lines[i].trim()))rows.push(lines[i].split('|').slice(1,-1).map(x=>x.trim()));i++}result.push(<div className="table-scroll" tabIndex={0} role="region" aria-label="Evidence table" key={'t'+i}><table><thead><tr>{rows[0].map((x,j)=><th key={j} scope="col">{x}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,j)=><tr key={j}>{r.map((x,k)=>k===0?<th scope="row" key={k}>{inline(x)}</th>:<td key={k}>{inline(x)}</td>)}</tr>)}</tbody></table></div>);continue}if(line.startsWith('- ')){const items=[];while(i<lines.length&&lines[i].trim().startsWith('- ')){items.push(<li key={i}>{inline(lines[i].trim().slice(2))}</li>);i++}result.push(<ul key={'u'+i}>{items}</ul>);continue}const hm=line.match(/^(#{1,3})\s(.+)/);if(hm){const L=hm[1].length, content=hm[2],id=L>1?slug(content):undefined;result.push(L===1?<h1 key={i}>{content}</h1>:L===2?<h2 id={id} key={i}>{content}</h2>:<h3 id={id} key={i}>{content}</h3>);i++;continue}let p=line;i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,3})\s|^- |^\|/.test(lines[i].trim())){p+=' '+lines[i].trim();i++}result.push(<p key={'p'+i}>{inline(p)}</p>)}return result},[source]);return <>{blocks}</>}
export function ContactForm(){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle'),[errors,setErrors]=useState<Record<string,string>>({});
 const summary=useRef<HTMLDivElement>(null);
 const required=['name','email','decision','deadline','consequence','material'];
 const validate=(id:string,value:string)=>{if(required.includes(id)&&!value.trim())return `${id[0].toUpperCase()+id.slice(1)} is required.`;if(id==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return 'Enter a valid email address.';return ''};
 const onBlur=(event:FocusEvent<HTMLInputElement|HTMLTextAreaElement>)=>{const {name,value}=event.currentTarget;if(!(name in errors))return;const message=validate(name,value);setErrors(current=>{const next={...current};if(message)next[name]=message;else delete next[name];return next})};
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),next:Record<string,string>={};for(const id of required){const message=validate(id,String(form.get(id)||''));if(message)next[id]=message}if(Object.keys(next).length){setErrors(next);setTimeout(()=>summary.current?.focus(),0);return}setErrors({});setState('sending');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});if(!response.ok)throw Error();setState('success')}catch{setState('error')}}
 const fields=[['name','Name','text'],['organization','Organization, optional','text'],['email','Email','email'],['decision','What decision needs to be made?','textarea'],['deadline','What is the deadline?','text'],['consequence','What happens if the decision is delayed or gets the wrong answer?','textarea'],['material','What material is already available?','textarea']];
 return <section className="contact-form-wrap" aria-labelledby="form-title"><h2 id="form-title">Start the conversation</h2><p>Fields marked required must be completed.</p>{Object.keys(errors).length>0&&<div className="error-summary" ref={summary} tabIndex={-1} role="alert"><b>Please correct the following:</b><ul>{Object.entries(errors).map(([id,message])=><li key={id}><a href={'#'+id}>{message}</a></li>)}</ul></div>}{state==='success'?<div className="success" role="status"><h3>Thank you. Your inquiry has been sent.</h3><p>DDA will review the decision and available material, then follow up about the smallest useful next step.</p></div>:<form onSubmit={submit} noValidate>{fields.map(([id,label,type])=><div className="field" key={id}><label htmlFor={id}>{label}{id!=='organization'&&' *'}</label>{type==='textarea'?<textarea id={id} name={id} onBlur={onBlur} aria-invalid={Boolean(errors[id])} aria-describedby={errors[id]?`${id}-error`:undefined}/>:<input id={id} name={id} type={type} onBlur={onBlur} aria-invalid={Boolean(errors[id])} aria-describedby={errors[id]?`${id}-error`:undefined}/>} {errors[id]&&<span className="field-error" id={`${id}-error`}>{errors[id]}</span>}</div>)}<p className="caution">Please do not send privileged, personal, or commercially confidential material in the initial message; DDA can arrange an appropriate transfer method if needed.</p><button className="public-button" disabled={state==='sending'}>{state==='sending'?'Sending inquiry…':'Send inquiry'} <ArrowRight/></button>{state==='error'&&<p role="alert" className="form-error">The inquiry could not be sent. Your entries are still here; please try again.</p>}</form>}<p className="no-engagement">Sending an inquiry does not create a client relationship or engagement; work begins only under agreed written terms.</p></section>
}
