import { useEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { pages } from '@/content/siteContent';

const links:Record<string,string>={'01-home.md':'/','02-what-we-do.md':'/what-we-do/','03-fiscal-impact-growth-modelling.md':'/what-we-do/fiscal-impact-growth-modelling/','04-official-community-plan-policy-analysis.md':'/what-we-do/official-community-plan-policy-analysis/','05-economic-development-strategy.md':'/what-we-do/economic-development-strategy/','06-labour-market-analysis.md':'/what-we-do/labour-market-analysis/','07-resource-sector-complex-planning-analysis.md':'/what-we-do/resource-sector-complex-planning-analysis/','08-long-range-financial-scenario-planning.md':'/what-we-do/long-range-financial-scenario-planning/','09-public-interest-research-evidence-packages.md':'/what-we-do/public-interest-research-evidence-packages/','10-who-we-are.md':'/who-we-are/','11-insights.md':'/insights/','12-insight-housing-target-delivery.md':'/insights/when-a-housing-target-outruns-delivery/','13-insight-trade-gap-workforce-number.md':'/insights/the-trade-gap-hidden-inside-a-workforce-number/','14-insight-what-a-flag-tells-you.md':'/insights/what-a-flag-tells-you/','15-selected-work.md':'/selected-work/','16-contact.md':'/contact/','17-privacy.md':'/privacy/','18-legal.md':'/legal/','19-terms.md':'/terms/','20-accessibility.md':'/accessibility/'};
function inline(s:string):ReactNode[]{ const out:ReactNode[]=[]; const re=/(\*\*([^*]+)\*\*|\[([^\]]+)\]\(\.\/([^\)]+)\))/g; let last=0,m; while((m=re.exec(s))){out.push(s.slice(last,m.index)); if(m[2])out.push(<strong key={m.index}>{m[2]}</strong>);else out.push(<Link key={m.index} to={links[m[4]]||'/'}>{m[3]} <ArrowRight aria-hidden="true"/></Link>);last=re.lastIndex}out.push(s.slice(last));return out }
const evidence:Record<string,{title:string;items:string[];finding:string}>={
 '/what-we-do/fiscal-impact-growth-modelling/':{title:'Scenario comparison structure',items:['Assumptions','Growth case','Timing','Revenue and cost','Interpretation'],finding:'The comparison identifies which assumption carries the result before a target becomes a commitment.'},
 '/what-we-do/official-community-plan-policy-analysis/':{title:'Policy-to-delivery trace',items:['Policy or target','Evidence basis','Implementation mechanism','Delivery condition','Unresolved gap'],finding:'Each step must remain supported before policy can be treated as a delivery mechanism.'},
 '/what-we-do/economic-development-strategy/':{title:'Opportunity screen',items:['Evidence','Local control','Timing','Capacity','Dependencies'],finding:'Opportunities are separated by what can move now, what requires preparation, and what should be monitored.'},
 '/what-we-do/labour-market-analysis/':{title:'Workforce decomposition',items:['Occupation','Qualification','Location','Mobility','Timing','Employer demand'],finding:'Usable workforce is the supply that remains after every relevant constraint is applied.'},
 '/what-we-do/resource-sector-complex-planning-analysis/':{title:'Dependency register',items:['Workforce','Infrastructure','Approvals','Housing','Logistics','Public services','Timing'],finding:'Named dependencies show which condition can reach the project date and who can act on it.'},
 '/what-we-do/long-range-financial-scenario-planning/':{title:'Assumptions register',items:['Assumption','Source and status','Time horizon','Sensitivity','Decision effect'],finding:'Material assumptions stay visible, testable, and connected to the choice they could change.'},
 '/what-we-do/public-interest-research-evidence-packages/':{title:'Claim-and-source register',items:['Claim or question','Evidence found','Source status','Conflict or gap','Implication'],finding:'Written evidence states keep uncertainty visible without implying certainty or privilege.'}
};
function EvidenceModule({config}:{config:{title:string;items:string[];finding:string}}){return <figure className="evidence-module" aria-labelledby="evidence-title"><figcaption id="evidence-title">{config.title}</figcaption><ol>{config.items.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,'0')}</span>{item}</li>)}</ol><p><strong>Interpretation:</strong> {config.finding}</p></figure>}
function Markdown({source,path}:{source:string;path:string}){const blocks=useMemo(()=>{const lines=source.trim().split('\n'), result:ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue}if(line.startsWith('|')){const rows:string[][]=[];while(i<lines.length&&lines[i].trim().startsWith('|')){if(!/^\|[\s:|-]+\|$/.test(lines[i].trim()))rows.push(lines[i].split('|').slice(1,-1).map(x=>x.trim()));i++}result.push(<div className="table-scroll" tabIndex={0} role="region" aria-label="Evidence table" key={'t'+i}><table><thead><tr>{rows[0].map((x,j)=><th key={j} scope="col">{x}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,j)=><tr key={j}>{r.map((x,k)=>k===0?<th scope="row" key={k}>{inline(x)}</th>:<td key={k}>{inline(x)}</td>)}</tr>)}</tbody></table></div>);continue}if(line.startsWith('- ')){const items=[];while(i<lines.length&&lines[i].trim().startsWith('- ')){items.push(<li key={i}>{inline(lines[i].trim().slice(2))}</li>);i++}result.push(<ul key={'u'+i}>{items}</ul>);continue}const hm=line.match(/^(#{1,3})\s(.+)/);if(hm){const L=hm[1].length, content=hm[2];result.push(L===1?<h1 key={i}>{content}</h1>:L===2?<h2 key={i}>{content}</h2>:<h3 key={i}>{content}</h3>);if(content==='The analysis'&&evidence[path])result.push(<EvidenceModule config={evidence[path]} key={'e'+i}/>);i++;continue}let p=line;i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,3})\s|^- |^\|/.test(lines[i].trim())){p+=' '+lines[i].trim();i++}result.push(<p key={'p'+i}>{inline(p)}</p>)}return result},[source,path]);return <>{blocks}</>}
function ContactForm(){const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle'),[errors,setErrors]=useState<string[]>([]);const summary=useRef<HTMLDivElement>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget), missing=['name','email','decision','deadline','consequence','material'].filter(x=>!String(f.get(x)||'').trim());if(missing.length){setErrors(missing);setTimeout(()=>summary.current?.focus(),0);return}setErrors([]);setState('sending');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(!r.ok)throw Error();setState('success')}catch{setState('error')}}return <section className="contact-form-wrap" aria-labelledby="form-title"><h2 id="form-title">Start the conversation</h2><p>Fields marked required must be completed.</p>{errors.length>0&&<div className="error-summary" ref={summary} tabIndex={-1} role="alert"><b>Please correct the following:</b><ul>{errors.map(x=><li key={x}><a href={'#'+x}>{x[0].toUpperCase()+x.slice(1)} is required.</a></li>)}</ul></div>}{state==='success'?<div className="success" role="status"><h3>Thank you. Your inquiry has been sent.</h3><p>DDA will review the decision and available material, then follow up about the smallest useful next step.</p></div>:<form onSubmit={submit} noValidate>{[['name','Name','text'],['organization','Organization, optional','text'],['email','Email','email'],['decision','What decision needs to be made?','textarea'],['deadline','What is the deadline?','text'],['consequence','What happens if the decision is delayed or gets the wrong answer?','textarea'],['material','What material is already available?','textarea']].map(([id,label,type])=><div className="field" key={id}><label htmlFor={id}>{label}{id!=='organization'&&' *'}</label>{type==='textarea'?<textarea id={id} name={id} aria-invalid={errors.includes(id)}/>:<input id={id} name={id} type={type} aria-invalid={errors.includes(id)}/>}</div>)}<p className="caution">Please do not send privileged, personal, or commercially confidential material in the initial message; DDA can arrange an appropriate transfer method if needed.</p><button className="primary-button" disabled={state==='sending'}>{state==='sending'?'Sending inquiry…':'Send inquiry'} <ArrowRight/></button>{state==='error'&&<p role="alert" className="form-error">The inquiry could not be sent. Your entries are still here; please try again.</p>}</form>}<p className="no-engagement">Sending an inquiry does not create a client relationship or engagement; work begins only under agreed written terms.</p></section>}
export default function WebsitePage(){const {pathname}=useLocation(), page=useRef<HTMLElement>(null), key=pathname==='/'?'/':pathname.endsWith('/')?pathname:pathname+'/';const source=pages[key];const isHome=key==='/',isArticle=key.startsWith('/insights/')&&key!=='/insights/',isUtility=['/privacy/','/legal/','/terms/','/accessibility/'].includes(key);useEffect(()=>{const root=page.current;if(!root||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const items=[...root.querySelectorAll<HTMLElement>('.markdown > h2, .markdown > h3, .markdown > .table-scroll, .contact-close')];root.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{rootMargin:'0px 0px -10%',threshold:.08});items.forEach(item=>observer.observe(item));return()=>observer.disconnect()},[key]);let display=source;if(key==='/contact/')display=source.split('## Start the conversation')[0];return <article ref={page} className={`public-page ${isHome?'home-page':''} ${isArticle?'article-page':''} ${isUtility?'utility-page':''} ${key==='/insights/'?'insights-page':''}`}><div className="hero-art" aria-hidden="true"><i/><i/><i/></div>{key==='/insights/'&&<div className="insights-underlay" aria-hidden="true"/>}{!isHome&&<div className="breadcrumb"><Link to="/">Home</Link><span>/</span><span aria-current="page">{source.match(/^# (.+)$/m)?.[1]}</span></div>}<div className="markdown"><Markdown source={display} path={key}/>{key==='/contact/'&&<ContactForm/>}</div>{!isHome&&!isUtility&&key!=='/contact/'&&<aside className="contact-close"><p className="eyebrow">Work with DDA</p><h2>Bring the decision and the deadline.</h2><p>Start with what must move, when it matters, and the condition that remains unclear.</p><Link className="primary-button" to="/contact/">Get in touch <ArrowRight/></Link></aside>}</article>}
