import { useEffect, useMemo, useRef, useState } from 'react';
import type { FocusEvent, FormEvent, ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { pageByRoute, pages, type PublicPage } from '@/content/siteContent';

const links:Record<string,string>={'01-home.md':'/','02-what-we-do.md':'/what-we-do/','03-fiscal-impact-growth-modelling.md':'/what-we-do/fiscal-impact-growth-modelling/','04-official-community-plan-policy-analysis.md':'/what-we-do/official-community-plan-policy-analysis/','05-economic-development-strategy.md':'/what-we-do/economic-development-strategy/','06-labour-market-analysis.md':'/what-we-do/labour-market-analysis/','07-resource-sector-complex-planning-analysis.md':'/what-we-do/resource-sector-complex-planning-analysis/','08-long-range-financial-scenario-planning.md':'/what-we-do/long-range-financial-scenario-planning/','09-public-interest-research-evidence-packages.md':'/what-we-do/public-interest-research-evidence-packages/','10-who-we-are.md':'/who-we-are/','11-insights.md':'/insights/','12-insight-housing-target-delivery.md':'/insights/when-a-housing-target-outruns-delivery/','13-insight-trade-gap-workforce-number.md':'/insights/the-trade-gap-hidden-inside-a-workforce-number/','14-insight-what-a-flag-tells-you.md':'/insights/what-a-flag-tells-you/','15-selected-work.md':'/selected-work/','16-contact.md':'/contact/','17-privacy.md':'/privacy/','18-legal.md':'/legal/','19-terms.md':'/terms/','20-accessibility.md':'/accessibility/'};
function inline(s:string):ReactNode[]{ const out:ReactNode[]=[]; const re=/(\*\*([^*]+)\*\*|\[([^\]]+)\]\(\.\/([^\)]+)\))/g; let last=0,m; while((m=re.exec(s))){out.push(s.slice(last,m.index)); if(m[2])out.push(<strong key={m.index}>{m[2]}</strong>);else out.push(<Link key={m.index} to={links[m[4]]||'/'}>{m[3]} <ArrowRight aria-hidden="true"/></Link>);last=re.lastIndex}out.push(s.slice(last));return out }
const evidence:Record<string,{title:string;items:string[];finding:string}>={
 '/what-we-do/fiscal-impact-growth-modelling/':{title:'Scenario comparison structure',items:['Assumptions','Growth case','Timing','Revenue and cost','Interpretation'],finding:'The comparison identifies which assumption carries the result before a target becomes a commitment.'},
 '/what-we-do/official-community-plan-policy-analysis/':{title:'Policy-to-delivery trace',items:['Policy or target','Evidence basis','Implementation mechanism','Delivery condition','Unresolved gap'],finding:'Each step must remain supported before policy can be treated as a delivery mechanism.'},
 '/what-we-do/economic-development-strategy/':{title:'Opportunity screen',items:['Evidence','Local control','Timing','Capacity','Dependencies'],finding:'Opportunities are separated by what can move now, what requires preparation, and what should be monitored.'},
 '/what-we-do/labour-market-analysis/':{title:'Workforce decomposition',items:['Occupation','Qualification','Location','Mobility','Timing','Employer demand'],finding:'Usable workforce is the supply that remains after every relevant constraint is applied.'},
 '/what-we-do/resource-sector-complex-planning-analysis/':{title:'Dependency register',items:['Workforce','Infrastructure','Approvals','Housing','Logistics','Public services','Timing'],finding:'Named dependencies show which condition can reach the project date and who can act on it.'},
 '/what-we-do/long-range-financial-scenario-planning/':{title:'Assumptions register',items:['Assumption','Source and status','Time horizon','Sensitivity','Decision effect'],finding:'Material assumptions stay visible, testable, and connected to the choice they could change.'},
 '/what-we-do/public-interest-research-evidence-packages/':{title:'Claim-and-source register',items:['Claim or question','Evidence found','Source status','Conflict or gap','Implication'],finding:'Written evidence states keep uncertainty visible without implying certainty or privilege.'}
};
function EvidenceModule({config}:{config:{title:string;items:string[];finding:string}}){return <figure className="evidence-module" aria-labelledby="evidence-title"><figcaption id="evidence-title">{config.title}</figcaption><ol>{config.items.map((item,index)=><li key={item}><span>{String(index+1).padStart(2,'0')}</span>{item}</li>)}</ol><p><strong>Interpretation:</strong> {config.finding}</p></figure>}
function Markdown({source,path}:{source:string;path:string}){const blocks=useMemo(()=>{const lines=source.trim().split('\n'), result:ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue}if(line.startsWith('|')){const rows:string[][]=[];while(i<lines.length&&lines[i].trim().startsWith('|')){if(!/^\|[\s:|-]+\|$/.test(lines[i].trim()))rows.push(lines[i].split('|').slice(1,-1).map(x=>x.trim()));i++}result.push(<div className="table-scroll" tabIndex={0} role="region" aria-label="Evidence table" key={'t'+i}><table><thead><tr>{rows[0].map((x,j)=><th key={j} scope="col">{x}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,j)=><tr key={j}>{r.map((x,k)=>k===0?<th scope="row" key={k}>{inline(x)}</th>:<td key={k}>{inline(x)}</td>)}</tr>)}</tbody></table></div>);continue}if(line.startsWith('- ')){const items=[];while(i<lines.length&&lines[i].trim().startsWith('- ')){items.push(<li key={i}>{inline(lines[i].trim().slice(2))}</li>);i++}result.push(<ul key={'u'+i}>{items}</ul>);continue}const hm=line.match(/^(#{1,3})\s(.+)/);if(hm){const L=hm[1].length, content=hm[2];result.push(L===1?<h1 key={i}>{content}</h1>:L===2?<h2 key={i}>{content}</h2>:<h3 key={i}>{content}</h3>);if(content==='The analysis'&&evidence[path])result.push(<EvidenceModule config={evidence[path]} key={'e'+i}/>);i++;continue}let p=line;i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,3})\s|^- |^\|/.test(lines[i].trim())){p+=' '+lines[i].trim();i++}result.push(<p key={'p'+i}>{inline(p)}</p>)}return result},[source,path]);return <>{blocks}</>}
function ContactForm(){
 const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle'),[errors,setErrors]=useState<Record<string,string>>({});
 const summary=useRef<HTMLDivElement>(null);
 const required=['name','email','decision','deadline','consequence','material'];
 const validate=(id:string,value:string)=>{if(required.includes(id)&&!value.trim())return `${id[0].toUpperCase()+id.slice(1)} is required.`;if(id==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return 'Enter a valid email address.';return ''};
 const onBlur=(event:FocusEvent<HTMLInputElement|HTMLTextAreaElement>)=>{const {name,value}=event.currentTarget;if(!(name in errors))return;const message=validate(name,value);setErrors(current=>{const next={...current};if(message)next[name]=message;else delete next[name];return next})};
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),next:Record<string,string>={};for(const id of required){const message=validate(id,String(form.get(id)||''));if(message)next[id]=message}if(Object.keys(next).length){setErrors(next);setTimeout(()=>summary.current?.focus(),0);return}setErrors({});setState('sending');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});if(!response.ok)throw Error();setState('success')}catch{setState('error')}}
 const fields=[['name','Name','text'],['organization','Organization, optional','text'],['email','Email','email'],['decision','What decision needs to be made?','textarea'],['deadline','What is the deadline?','text'],['consequence','What happens if the decision is delayed or gets the wrong answer?','textarea'],['material','What material is already available?','textarea']];
 return <section className="contact-form-wrap" aria-labelledby="form-title"><h2 id="form-title">Start the conversation</h2><p>Fields marked required must be completed.</p>{Object.keys(errors).length>0&&<div className="error-summary" ref={summary} tabIndex={-1} role="alert"><b>Please correct the following:</b><ul>{Object.entries(errors).map(([id,message])=><li key={id}><a href={'#'+id}>{message}</a></li>)}</ul></div>}{state==='success'?<div className="success" role="status"><h3>Thank you. Your inquiry has been sent.</h3><p>DDA will review the decision and available material, then follow up about the smallest useful next step.</p></div>:<form onSubmit={submit} noValidate>{fields.map(([id,label,type])=><div className="field" key={id}><label htmlFor={id}>{label}{id!=='organization'&&' *'}</label>{type==='textarea'?<textarea id={id} name={id} onBlur={onBlur} aria-invalid={Boolean(errors[id])} aria-describedby={errors[id]?`${id}-error`:undefined}/>:<input id={id} name={id} type={type} onBlur={onBlur} aria-invalid={Boolean(errors[id])} aria-describedby={errors[id]?`${id}-error`:undefined}/>} {errors[id]&&<span className="field-error" id={`${id}-error`}>{errors[id]}</span>}</div>)}<p className="caution">Please do not send privileged, personal, or commercially confidential material in the initial message; DDA can arrange an appropriate transfer method if needed.</p><button className="primary-button" disabled={state==='sending'}>{state==='sending'?'Sending inquiry…':'Send inquiry'} <ArrowRight/></button>{state==='error'&&<p role="alert" className="form-error">The inquiry could not be sent. Your entries are still here; please try again.</p>}</form>}<p className="no-engagement">Sending an inquiry does not create a client relationship or engagement; work begins only under agreed written terms.</p></section>
}
function Breadcrumbs({page}:{page:PublicPage}){const capability=page.type==='capability-detail',article=page.type==='article';return <nav className="breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span aria-hidden="true">/</span>{capability&&<><Link to="/what-we-do/">What we do</Link><span aria-hidden="true">/</span></>}{article&&<><Link to="/insights/">Insights</Link><span aria-hidden="true">/</span></>}<span aria-current="page">{page.title}</span></nav>}
function OnThisPage({source}:{source:string}){const headings=[...source.matchAll(/^## (.+)$/gm)].map(match=>match[1]).filter(title=>title!=='Work with DDA');if(headings.length<3)return null;return <aside className="on-page" aria-label="On this page"><b>On this page</b><ol>{headings.map(title=><li key={title}>{title}</li>)}</ol></aside>}
function PublicTemplate({page,source,root}:{page:PublicPage;source:string;root:import('react').RefObject<HTMLElement|null>}){const isHome=page.type==='home', display=page.type==='contact'?source.split('## Start the conversation')[0]:source;return <article ref={root} className={`public-page template-${page.type} ${isHome?'home-page':''} ${page.type==='article'?'article-page':''} ${page.type==='utility'?'utility-page':''} ${page.type==='insights-hub'?'insights-page':''}`}><div className="hero-art" aria-hidden="true"><i/><i/><i/></div>{page.type==='insights-hub'&&<div className="insights-underlay" aria-hidden="true"/>}{!isHome&&<Breadcrumbs page={page}/>} {page.type==='article'&&<div className="article-meta"><span>Perspective</span><span>{page.topics[0]}</span><span>{page.readTime}</span></div>}<div className="template-grid"><div className="markdown"><Markdown source={display} path={page.route}/>{page.type==='contact'&&<ContactForm/>}</div>{['capability-detail','article','utility'].includes(page.type)&&<OnThisPage source={display}/>}</div>{!isHome&&!['utility','contact'].includes(page.type)&&<aside className="contact-close"><p className="eyebrow">Work with DDA</p><h2>Bring the decision and the deadline.</h2><p>Start with what must move, when it matters, and the condition that remains unclear.</p><Link className="primary-button" to="/contact/">Discuss a decision <ArrowRight/></Link></aside>}</article>}
export default function WebsitePage(){const {pathname}=useLocation(),root=useRef<HTMLElement>(null),key=pathname==='/'?'/':pathname.endsWith('/')?pathname:pathname+'/';const source=pages[key],page=pageByRoute[key];useEffect(()=>{const node=root.current;if(!node||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const items=[...node.querySelectorAll<HTMLElement>('.markdown > h2, .markdown > h3, .markdown > .table-scroll, .contact-close')];node.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{rootMargin:'0px 0px -10%',threshold:.08});items.forEach(item=>observer.observe(item));return()=>observer.disconnect()},[key]);return <PublicTemplate page={page} source={source} root={root}/>}
