import home from '../../.mds/01-home.md?raw'; import what from '../../.mds/02-what-we-do.md?raw';
import p03 from '../../.mds/03-fiscal-impact-growth-modelling.md?raw'; import p04 from '../../.mds/04-official-community-plan-policy-analysis.md?raw'; import p05 from '../../.mds/05-economic-development-strategy.md?raw'; import p06 from '../../.mds/06-labour-market-analysis.md?raw'; import p07 from '../../.mds/07-resource-sector-complex-planning-analysis.md?raw'; import p08 from '../../.mds/08-long-range-financial-scenario-planning.md?raw'; import p09 from '../../.mds/09-public-interest-research-evidence-packages.md?raw';
import who from '../../.mds/10-who-we-are.md?raw'; import insights from '../../.mds/11-insights.md?raw'; import p12 from '../../.mds/12-insight-housing-target-delivery.md?raw'; import p13 from '../../.mds/13-insight-trade-gap-workforce-number.md?raw'; import p14 from '../../.mds/14-insight-what-a-flag-tells-you.md?raw'; import selected from '../../.mds/15-selected-work.md?raw'; import contact from '../../.mds/16-contact.md?raw'; import privacy from '../../.mds/17-privacy.md?raw'; import legal from '../../.mds/18-legal.md?raw'; import terms from '../../.mds/19-terms.md?raw'; import accessibility from '../../.mds/20-accessibility.md?raw';

export type PageTemplate='home'|'capability-hub'|'capability'|'about'|'insights-hub'|'article'|'work'|'contact'|'utility';
export type PublicPage={path:string;source:string;title:string;description:string;template:PageTemplate;topic:string;parent?:string;related?:string[]};
const define=(path:string,source:string,template:PageTemplate,topic:string,description:string,parent?:string,related?:string[]):PublicPage=>({path,source,title:source.match(/^# (.+)$/m)?.[1]??'DDA',description,template,topic,parent,related});
export const publicPages:PublicPage[]=[
 define('/',home,'home','DDA','Strategic analysis and decision design for complex public and regulated systems.'),
 define('/what-we-do/',what,'capability-hub','Capabilities','Diagnose controlling conditions, model consequences, design responses, and equip decision-makers.'),
 define('/what-we-do/fiscal-impact-growth-modelling/',p03,'capability','Growth and fiscal','Connect growth, capacity, infrastructure, cost, and revenue before a target becomes a commitment.','/what-we-do/',['/insights/when-a-housing-target-outruns-delivery/','/selected-work/']),
 define('/what-we-do/official-community-plan-policy-analysis/',p04,'capability','Planning and policy','Trace plans and policy choices through the conditions required for delivery.','/what-we-do/',['/insights/when-a-housing-target-outruns-delivery/','/selected-work/']),
 define('/what-we-do/economic-development-strategy/',p05,'capability','Regional economy','Build executable strategy around readiness, dependencies, ownership, and timing.','/what-we-do/',['/selected-work/']),
 define('/what-we-do/labour-market-analysis/',p06,'capability','Labour and workforce','Find the occupation, qualification, mobility, location, or date controlling workforce supply.','/what-we-do/',['/insights/the-trade-gap-hidden-inside-a-workforce-number/','/selected-work/']),
 define('/what-we-do/resource-sector-complex-planning-analysis/',p07,'capability','Major projects','Connect workforce, infrastructure, logistics, approvals, communities, and schedule.','/what-we-do/',['/selected-work/']),
 define('/what-we-do/long-range-financial-scenario-planning/',p08,'capability','Scenarios and finance','Test long-range choices against uncertainty, sensitivity, and changing conditions.','/what-we-do/',['/insights/what-a-flag-tells-you/','/selected-work/']),
 define('/what-we-do/public-interest-research-evidence-packages/',p09,'capability','Institutions and evidence','Separate claims, sources, assumptions, conflicts, and unknowns for accountable decisions.','/what-we-do/',['/insights/what-a-flag-tells-you/','/selected-work/']),
 define('/who-we-are/',who,'about','About DDA','A principal-led strategic analysis and decision-design practice.','/'),
 define('/insights/',insights,'insights-hub','Insights','Analysis that clarifies decisions, exposes assumptions, and shows where action is stuck.'),
 define('/insights/when-a-housing-target-outruns-delivery/',p12,'article','Growth and land use','Trace a housing target through land, servicing, construction economics, financing, and delivery.','/insights/',['/what-we-do/official-community-plan-policy-analysis/','/insights/the-trade-gap-hidden-inside-a-workforce-number/']),
 define('/insights/the-trade-gap-hidden-inside-a-workforce-number/',p13,'article','Labour and major projects','Find the trade, qualification, location, mobility condition, or date hidden by an aggregate.','/insights/',['/what-we-do/labour-market-analysis/','/insights/what-a-flag-tells-you/']),
 define('/insights/what-a-flag-tells-you/',p14,'article','Decision quality','Identify a consequential evidence gap and the shortest responsible route to resolve it.','/insights/',['/what-we-do/public-interest-research-evidence-packages/','/insights/when-a-housing-target-outruns-delivery/']),
 define('/selected-work/',selected,'work','Selected work','Verified examples structured around the decision, controlling condition, analysis, shift, and instrument.'),
 define('/contact/',contact,'contact','Contact','Bring the decision, deadline, consequence, and available material.'),
 define('/privacy/',privacy,'utility','Information','How DDA handles personal information.'), define('/legal/',legal,'utility','Information','Legal information for the DDA website.'), define('/terms/',terms,'utility','Information','Terms governing use of the DDA website.'), define('/accessibility/',accessibility,'utility','Information','DDA accessibility commitments and contact information.')
];
export const pageManifest=Object.fromEntries(publicPages.map(page=>[page.path,page])) as Record<string,PublicPage>;
export const pages=Object.fromEntries(publicPages.map(page=>[page.path,page.source])) as Record<string,string>;
export const routeAliases:Record<string,string>={...Object.fromEntries(publicPages.filter(x=>x.path!='/').map(x=>[x.path.slice(0,-1),x.path]))};
