import { useEffect, useMemo, useReducer, useState } from 'react';
import './EngagementCommandCenter.css';

type M='command'|'calendar'|'flags'|'documents'|'evidence'|'finance'|'contracts'|'stakeholders';
const empty={engagements:[],flags:[],deliverables:[],evidence:[],events:[],finance:[],contracts:[],stakeholders:[]} as any;
const k='dda_db'; const ak='dda_auth'; const uuid=()=>crypto.randomUUID(); const today=()=>new Date().toISOString().slice(0,10);
const reducer=(s:any,a:any)=>{ if(a.type==='set') return a.payload; if(a.type==='patch') return {...s,...a.payload}; return s; };
const isUUID=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);

export default function EngagementCommandCenter(){
const [authed,setAuthed]=useState(localStorage.getItem(ak)==='true'); const [u,setU]=useState(''); const [p,setP]=useState(''); const [err,setErr]=useState('');
const [state,dispatch]=useReducer(reducer,empty); const [module,setModule]=useState<M>('command'); const [collapsed,setCollapsed]=useState(false); const [filterEng,setFilterEng]=useState<string|null>(null);
const [consoleOpen,setConsoleOpen]=useState(false); const [ops,setOps]=useState('[]'); const [consoleOut,setConsoleOut]=useState<string[]>([]); const [toast,setToast]=useState(''); const [settings,setSettings]=useState(false);
useEffect(()=>{ if(!authed) return; try{ const raw=localStorage.getItem(k); if(raw){ const parsed=JSON.parse(raw); dispatch({type:'set',payload:{...empty,...parsed}}); } else { dispatch({type:'set',payload:empty}); } }catch{ dispatch({type:'set',payload:empty}); } },[authed]);
useEffect(()=>{ if(authed) localStorage.setItem(k,JSON.stringify(state)); },[state,authed]);
useEffect(()=>{ if(!toast) return; const t=setTimeout(()=>setToast(''),3000); return ()=>clearTimeout(t); },[toast]);
const engagementStatus=(id:string)=>{ const t=new Date(); const atRisk=state.deliverables.some((d:any)=>d.engagement_id===id&&d.status!=='delivered'&&new Date(d.due_date)<t); const flagged=state.flags.some((f:any)=>f.engagement_id===id&&f.status==='open'&&f.owner==='client'&&((t.getTime()-new Date(f.last_activity_date).getTime())/86400000)>14); return atRisk?'at_risk':flagged?'flagged':'on_track'; };
const deliverableStale=(d:any)=>d.evidence_ids?.some((eid:string)=>{const e=state.evidence.find((x:any)=>x.id===eid); return e && new Date(e.last_updated)>new Date(d.last_edited);});
const openFlags=state.flags.filter((f:any)=>f.status==='open');
const overdueInvoices=useMemo(()=>state.finance.flatMap((f:any)=>f.invoices||[]).filter((i:any)=>!i.paid_date&&new Date(i.due_date)<new Date()).length,[state.finance]);
const staleCount=useMemo(()=>state.deliverables.filter((d:any)=>deliverableStale(d)).length,[state.deliverables,state.evidence]);
const weakContracts=useMemo(()=>state.contracts.filter((c:any)=>!c.clauses?.termination_for_cause||!c.clauses?.mutual_indemnity||!c.clauses?.mandatory_mediation).length,[state.contracts]);
const byName=(target:string,id:string,source:any)=>{const map:any={engagement:['engagements','name'],flag:['flags','title'],deliverable:['deliverables','name'],stakeholder:['stakeholders','name'],evidence:['evidence','metric']}; const m=map[target]; if(!m) return {err:'Name resolution not supported'}; const hits=(source as any)[m[0]].filter((x:any)=>String(x[m[1]]||'').toLowerCase().includes(id.toLowerCase())); if(hits.length===1)return {id:hits[0].id,msg:`Resolved '${id}' → ${hits[0].id}`}; if(hits.length===0)return {err:`No match for '${id}'`}; return {err:`Ambiguous '${id}': ${hits.map((h:any)=>h[m[1]]).join(', ')}`}; };
const applySequence=(dry:boolean)=>{ let s=JSON.parse(JSON.stringify(state)); const out:string[]=[]; const fail=(m:string)=>{out.push(`ERROR: ${m}`); if(!dry) throw new Error(m);};
  const touch=(r:any)=>{if('last_updated'in r)r.last_updated=today(); if('last_edited'in r)r.last_edited=today();};
  const seq=JSON.parse(ops);
  for(const o of seq){ const collectionMap:Record<string,string>={engagement:'engagements',flag:'flags',deliverable:'deliverables',evidence:'evidence',event:'events',finance:'finance',contract:'contracts',stakeholder:'stakeholders'}; const arrKey=collectionMap[o.target]; let id=o.id as string|null; if(id && !isUUID(id)){const r=byName(o.target,id,s); if((r as any).err){fail((r as any).err); break;} id=(r as any).id; out.push((r as any).msg);} const arr=(s as any)[arrKey]; if(!arr){fail(`Unknown target ${o.target}`); break;}
    if(o.op==='CREATE'){const rec={id:uuid(),...o.fields}; arr.push(rec); out.push(`${dry?'Would create':'Created'} ${o.target}: ${rec.id}`);}
    else if(o.op==='UPDATE'){const i=arr.findIndex((x:any)=>x.id===id); if(i<0){fail(`Record not found ${o.target} ${id}`); break;} arr[i]={...arr[i],...o.fields}; touch(arr[i]); out.push(`${dry?'Would update':'Updated'} ${o.target} ${id}`);}
    else if(o.op==='RESOLVE_FLAG'){const i=s.flags.findIndex((x:any)=>x.id===id&&x.status==='open'); if(i<0){fail(`Open flag not found ${id}`); break;} s.flags[i]={...s.flags[i],status:'resolved',resolved_date:today(),resolution_value:o.fields.resolution_value}; let evCount=0,delCount=0; s.evidence=s.evidence.map((e:any)=>{if(e.linked_flag_id===id){evCount++; const old=e.value; e={...e,value:String(o.fields.resolution_value),classification:'ACTUAL',last_updated:today(),change_log:[...(e.change_log||[]),{date:today(),old_value:String(old),new_value:String(o.fields.resolution_value),reason:'FLAG resolved'}]}; s.deliverables=s.deliverables.map((d:any)=>d.engagement_id===e.engagement_id&&d.evidence_ids?.includes(e.id)?(delCount++,{...d,last_edited:'1970-01-01'}):d);} return e;}); out.push(`${dry?'Would resolve':'Resolved'} FLAG ${id}. Updated ${evCount} evidence entries. Marked ${delCount} deliverables stale.`);}
    else if(o.op==='ADVANCE_DELIVERABLE'){const order=['not_started','in_progress','draft_complete','under_review','revised','final','delivered']; const i=s.deliverables.findIndex((x:any)=>x.id===id); if(i<0){fail(`Deliverable not found ${id}`); break;} const cur=s.deliverables[i]; const ns=o.fields?.status||order[Math.min(order.indexOf(cur.status)+1,order.length-1)]; const v=(cur.version||0)+1; s.deliverables[i]={...cur,status:ns,version:v,last_edited:today(),versions:[...(cur.versions||[]),{version_number:v,date:today(),notes:o.fields?.notes||''}]}; out.push(`${dry?'Would advance':'Advanced'} ${cur.name} to ${ns} (v${v})`);}
    else if(o.op==='LOG_HOURS'){const i=s.finance.findIndex((x:any)=>x.id===id); if(i<0){fail(`Finance not found ${id}`); break;} s.finance[i].logged_hours=[...(s.finance[i].logged_hours||[]),{date:o.fields.date,hours:Number(o.fields.hours),description:o.fields.description||''}]; out.push(`${dry?'Would log':'Logged'} ${o.fields.hours}h`);}
    else if(o.op==='ADD_INTERACTION'){const i=s.stakeholders.findIndex((x:any)=>x.id===id); if(i<0){fail(`Stakeholder not found ${id}`); break;} s.stakeholders[i].interaction_history=[...(s.stakeholders[i].interaction_history||[]),o.fields]; if(!s.stakeholders[i].engagement_ids.includes(o.fields.engagement_id)) s.stakeholders[i].engagement_ids.push(o.fields.engagement_id); out.push(`${dry?'Would add':'Added'} interaction to ${s.stakeholders[i].name}`);}
    else if(o.op==='BULK_EVIDENCE'){let c=0,u=0,m=0; for(const e of (o.fields.entries||[])){ if(e.id){const i=s.evidence.findIndex((x:any)=>x.id===e.id); if(i>=0){const old=s.evidence[i].value; s.evidence[i]={...s.evidence[i],...e,last_updated:today(),change_log:[...(s.evidence[i].change_log||[]),{date:today(),old_value:String(old),new_value:String(e.value),reason:e.reason||'Bulk update'}]}; u++; s.deliverables=s.deliverables.map((d:any)=>d.evidence_ids?.includes(e.id)?(m++,{...d,last_edited:'1970-01-01'}):d);} } else {s.evidence.push({id:uuid(),change_log:[],...e,last_updated:today()}); c++;}} out.push(`${dry?'Would process':'Processed'} ${c+u} evidence entries: ${c} created, ${u} updated, ${m} deliverables marked stale`); }
    else {fail(`Unknown operation type: ${o.op}`); break;} 
  }
  if(!dry){dispatch({type:'set',payload:s}); setToast('Update applied'); setConsoleOpen(false);} setConsoleOut(out);
};
if(!authed) return <div className='ecc-root'><div className='ecc-login'><form onSubmit={e=>{e.preventDefault(); if(u==='DDA'&&p==='daviddoyle'){localStorage.setItem(ak,'true'); setAuthed(true); setErr('');} else setErr('Invalid credentials');}}><h1 className='ecc-title'>DDA</h1><input className='ecc-input' placeholder='Username' value={u} onChange={e=>setU(e.target.value)}/><input className='ecc-input' placeholder='Password' type='password' value={p} onChange={e=>setP(e.target.value)}/><button className='ecc-btn'>Enter</button>{err&&<div>{err}</div>}</form></div></div>;
return <div className='ecc-root'><div className='ecc-shell'><div className='ecc-header'><strong className='ecc-title'>DDA Engagement Command Center</strong><div><button className='ecc-btn' onClick={()=>setConsoleOpen(true)}>&gt;_</button> <button className='ecc-btn' onClick={()=>setSettings(true)}>⚙</button> <button className='ecc-btn' onClick={()=>{localStorage.removeItem(ak);setAuthed(false);}}>Logout</button></div></div><div className='ecc-body'><aside className={`ecc-rail ${collapsed?'collapsed':''}`}>{(['command','calendar','flags','documents','evidence','finance','contracts','stakeholders'] as M[]).map(m=><button key={m} className={`ecc-btn ecc-nav ${module===m?'active':''}`} onClick={()=>setModule(m)}>{collapsed?m[0].toUpperCase():m}{!collapsed&&m==='flags'&&` (${openFlags.length})`}{!collapsed&&m==='documents'&&` (${staleCount})`}{!collapsed&&m==='finance'&&` (${overdueInvoices})`}{!collapsed&&m==='contracts'&&` (${weakContracts})`}</button>)}<button className='ecc-btn' onClick={()=>setCollapsed(!collapsed)}>{collapsed?'»':'«'}</button></aside><main className='ecc-main'>
{module==='command'&&(<div>{state.engagements.length===0?<div className='ecc-empty'>No active engagements. Create your first engagement to begin.<div><button className='ecc-btn' onClick={()=>setModule('flags')}>Create Engagement</button></div></div>:<><div className='ecc-grid'>{state.engagements.map((e:any)=><div className='ecc-card' key={e.id} onClick={()=>setFilterEng(filterEng===e.id?null:e.id)}><b>{e.name}</b><div>{e.client_name}</div><div>{e.phase}</div><progress value={e.completion_pct} max={100}/><div>{e.next_milestone} {e.next_milestone_date}</div><div className='ecc-badge' style={{background:engagementStatus(e.id)==='on_track'?'#4caf7d':engagementStatus(e.id)==='flagged'?'#c8922a':'#c84a4a'}}>{engagementStatus(e.id)}</div></div>)}</div><div className='ecc-card'>FLAG Summary {openFlags.slice(0,5).map((f:any)=><div key={f.id}>{f.title}</div>)}<button className='ecc-btn' onClick={()=>setModule('flags')}>View All</button></div></>}</div>)}
{module!=='command'&&<div className='ecc-card'>Module: {module} {((state as any)[module==='documents'?'deliverables':module==='calendar'?'events':module]||[]).length===0&&<div className='ecc-empty'>{module==='flags'?'No open FLAGs.':module==='documents'?'No deliverables tracked.':module==='evidence'?'No evidence entries.':module==='finance'?'No financial records.':module==='contracts'?'No contracts.':module==='stakeholders'?'No contacts.':'No events.'}</div>}</div>}
</main></div></div>
{consoleOpen&&<div className='ecc-modal'><div className='ecc-modal-panel'><h3>Update Console</h3><textarea className='ecc-textarea ecc-mono' placeholder='Paste operation sequence here…' value={ops} onChange={e=>setOps(e.target.value)}/><div><button className='ecc-btn' onClick={()=>{try{applySequence(true);}catch(e:any){setConsoleOut([`ERROR: ${e.message}`]);}}}>Preview</button> <button className='ecc-btn' onClick={()=>{try{applySequence(false);}catch(e:any){setConsoleOut([`ERROR: ${e.message}`]);}}}>Apply</button> <button className='ecc-btn' onClick={()=>setConsoleOpen(false)}>Cancel</button></div>{consoleOut.length>0&&<div className='ecc-card ecc-mono'>{consoleOut.map((l,i)=><div key={i} style={{color:l.startsWith('ERROR')?'#c84a4a':undefined}}>{l}</div>)}</div>}</div></div>}
{settings&&<div className='ecc-drawer'><h3>Settings</h3><button className='ecc-btn' onClick={()=>{if(confirm('Clear all data?')){localStorage.removeItem(k); dispatch({type:'set',payload:empty});}}}>Clear All Data</button><button className='ecc-btn' onClick={()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(b); a.download=`dda_backup_${today()}.json`; a.click();}}>Export Data</button><input type='file' onChange={async e=>{const f=e.target.files?.[0]; if(!f) return; const t=await f.text(); const j=JSON.parse(t); if(confirm('Replace current data?')) dispatch({type:'set',payload:{...empty,...j}});}}/><button className='ecc-btn' onClick={()=>{localStorage.removeItem(ak);setAuthed(false);}}>Logout</button><button className='ecc-btn' onClick={()=>setSettings(false)}>Close</button></div>}
{toast&&<div className='ecc-toast'>{toast}</div>}
</div>;
}
