export type ModuleKey = 'command'|'calendar'|'flags'|'documents'|'evidence'|'finance'|'contracts'|'stakeholders';
export interface Engagement { id:string; name:string; client_name:string; phase:string; phase_index:number; total_phases:number; completion_pct:number; next_milestone:string; next_milestone_date:string; start_date:string; end_date:string; contract_value:number; budget_hours:number; notes:string; }
export interface Flag { id:string; engagement_id:string; title:string; description:string; priority:'critical'|'high'|'medium'|'low'; status:'open'|'resolved'; resolution_path:string; owner:'doyle'|'client'; client_contact_id:string; opened_date:string; resolved_date:string|null; last_activity_date:string; blocks_deliverable_id:string|null; resolution_value:string|null; }
export interface VersionEntry { version_number:number; date:string; notes:string; }
export interface Deliverable { id:string; engagement_id:string; name:string; phase:string; due_date:string; status:'not_started'|'in_progress'|'draft_complete'|'under_review'|'revised'|'final'|'delivered'; version:number; versions:VersionEntry[]; evidence_ids:string[]; last_edited:string; file_url:string|null; notes:string; }
export interface ChangeLogEntry { date:string; old_value:string; new_value:string; reason:string; }
export interface EvidenceEntry { id:string; engagement_id:string; metric:string; value:string; unit:string; geography:string; reference_year:number; classification:'FLAG'|'ACTUAL'|'DERIVED'|'ASSUMPTION'; source:string; source_date:string; derivation:string; notes:string; resolution_path:string; linked_flag_id:string|null; last_updated:string; change_log:ChangeLogEntry[]; }
export interface CalendarEvent { id:string; engagement_id:string|null; title:string; type:'stakeholder_meeting'|'council_presentation'|'public_hearing'|'rfp_deadline'|'contract_deadline'|'invoice_due'|'milestone'|'travel'|'other'; start_datetime:string; end_datetime:string; location:string; attendee_ids:string[]; notes:string; }
export interface Invoice { invoice_id:string; amount:number; milestone_name:string; issued_date:string; due_date:string; paid_date:string|null; status:'draft'|'issued'|'paid'|'overdue'; }
export interface FinanceRecord { id:string; engagement_id:string; budget_hours:number; contract_value:number; payment_terms_days:number; logged_hours:{date:string;hours:number;description:string}[]; invoices:Invoice[]; }
export interface Contract { id:string; engagement_id:string; client_name:string; status:'draft'|'negotiating'|'signed'|'expired'; signed_date:string|null; expiry_date:string|null; renewal_option:boolean; clauses:{termination_for_cause:boolean; mutual_indemnity:boolean; mandatory_mediation:boolean}; modified_clauses:string[]; notes:string; file_url:string|null; }
export interface Interaction { date:string; type:'meeting'|'email'|'call'|'deliverable_sent'; engagement_id:string; notes:string; deliverable_id:string|null; }
export interface Stakeholder { id:string; name:string; organization:string; role:string; email:string; phone:string; engagement_ids:string[]; tags:string[]; interaction_history:Interaction[]; }
export interface DBState { engagements:Engagement[]; flags:Flag[]; deliverables:Deliverable[]; evidence:EvidenceEntry[]; events:CalendarEvent[]; finance:FinanceRecord[]; contracts:Contract[]; stakeholders:Stakeholder[]; }
export interface Operation { op:string; target:string; id:string|null; fields:Record<string,unknown>; }
