import { ArrowRight, Check } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { PublicPage } from '@/content/siteContent';
import { pageManifest } from '@/content/siteContent';
import { ContactForm, Markdown } from '@/components/public/MarkdownContent';

const section=(source:string,title:string)=>{const marker=`## ${title}`;const start=source.indexOf(marker);if(start<0)return '';const next=source.indexOf('\n## ',start+marker.length);return source.slice(start,next<0?undefined:next)};
const intro=(source:string)=>source.slice(0,source.search(/^## /m));
const children=(chunk:string)=>chunk.split(/^### /m).slice(1).map(part=>{const [title,...body]=part.trim().split('\n');return {title,body:body.join('\n').trim()}});
const bodyWithoutHeading=(chunk:string)=>chunk.replace(/^## .+\n+/,'');
const titleOf=(source:string)=>source.match(/^# (.+)$/m)?.[1]??'';

function Crumb({page}:{page:PublicPage}){return <nav className="public-crumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span>{page.parent&&page.parent!=='/'&&<><Link to={page.parent}>{pageManifest[page.parent].title}</Link><span>/</span></>}<span aria-current="page">{page.title}</span></nav>}
function PageHero({page,eyebrow='Strategic analysis',showCta=true}:{page:PublicPage;eyebrow?:string;showCta?:boolean}){const copy=intro(page.source).replace(/^# .+\n+/,'').trim()||page.description;return <header className="page-hero"><div className="public-container"><Crumb page={page}/><p className="section-label">{eyebrow}</p><h1>{page.title}</h1><div className="page-hero-dek"><Markdown source={copy} path={page.path}/></div>{showCta&&<Link className="public-button" to="/contact/">Discuss a decision <ArrowRight/></Link>}</div></header>}
function ContactBand(){return <section className="decision-band"><div className="public-container"><p className="section-label">Work with DDA</p><h2>Bring the decision.</h2><p>Start with what must move, when it matters, and the condition that remains unclear.</p><Link className="public-button light" to="/contact/">Discuss a decision <ArrowRight/></Link></div></section>}
function Metadata({text}:{text:string}){return <p className="card-meta">{text.replace(/\*\*/g,'')}</p>}

export function HomeTemplate({page}:{page:PublicPage}){const insightCards=children(section(page.source,'Our latest insights')),workCards=children(section(page.source,'Selected work'));return <div className="home-template">
 <section className="home-hero"><div className="hero-grid public-container"><div><p className="section-label">Strategic analysis · Decision design</p><h1>{titleOf(page.source)}</h1><p className="hero-dek">DDA is a strategic analysis and decision-design practice for complex public and regulated systems.</p><p className="hero-support">We connect economics, policy, infrastructure, labour, institutions, and timing to identify the condition that matters most.</p><div className="hero-actions"><Link className="public-button light" to="/what-we-do/">Explore what we do <ArrowRight/></Link><Link className="text-link inverse" to="/selected-work/">See selected work <ArrowRight/></Link></div></div><div className="hero-system" aria-hidden="true"><span>Evidence</span><span>Conditions</span><span>Consequences</span><i/></div></div></section>
 <section className="home-insights public-section"><div className="public-container"><div className="section-head"><div><p className="section-label">Insights</p><h2>Our latest insights</h2></div><Link className="text-link" to="/insights/">View all insights <ArrowRight/></Link></div><div className="insight-layout">{insightCards.map((card,index)=><article className={`editorial-card ${index===0?'lead':''}`} key={card.title}><span className="card-index">0{index+1}</span><h3>{card.title}</h3><Markdown source={card.body.replace(/\[([^\]]+)\]\([^)]+\)/g,'')} path={page.path}/><Metadata text={card.body.match(/\*\*[^*]+\*\*/)?.[0]??'DDA insight'}/><Link aria-label={`Read ${card.title}`} to={['/insights/when-a-housing-target-outruns-delivery/','/insights/the-trade-gap-hidden-inside-a-workforce-number/','/insights/what-a-flag-tells-you/'][index]}>Read the insight <ArrowRight/></Link></article>)}</div></div></section>
 <section className="home-work public-section"><div className="public-container"><div className="section-head"><div><p className="section-label">Selected work</p><h2>Selected work</h2></div><Link className="text-link inverse" to="/selected-work/">See selected work <ArrowRight/></Link></div><div className="proof-grid">{workCards.slice(0,3).map((card,index)=><article key={card.title}><span>0{index+1}</span><h3>{card.title}</h3><Markdown source={card.body.replace(/\[[^\]]+\]\([^)]+\)/g,'')} path={page.path}/></article>)}</div></div></section><ContactBand/></div>}

export function CapabilityHubTemplate({page}:{page:PublicPage}){const capabilities=children(section(page.source,'Four capabilities, one connected practice')),services=children(section(page.source,'Explore our services'));return <><PageHero page={page} eyebrow="What we do"/><main className="public-container"><section className="public-section"><div className="section-head"><div><p className="section-label">Connected practice</p><h2>Diagnose. Model. Design. Equip.</h2></div></div><div className="four-capabilities">{capabilities.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><Markdown source={item.body} path={page.path}/></article>)}</div></section><section className="public-section service-section"><p className="section-label">Seven applications</p><h2>Where DDA applies the practice.</h2><div className="service-grid">{services.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><Markdown source={item.body} path={page.path}/></article>)}</div></section><section className="method-standard"><Markdown source={section(page.source,'One standard across the work')} path={page.path}/></section></main><ContactBand/></>}

const chains:Record<string,string[]>={
 '/what-we-do/fiscal-impact-growth-modelling/':['Assumptions','Growth case','Timing','Revenue and cost','Decision'],
 '/what-we-do/official-community-plan-policy-analysis/':['Policy','Zoning','Servicing','Land readiness','Delivery'],
 '/what-we-do/economic-development-strategy/':['Opportunity','Readiness','Local control','Dependencies','Sequence'],
 '/what-we-do/labour-market-analysis/':['Regional workforce','Relevant occupation','Required qualification','Available location','Mobility','Timing','Usable workforce'],
 '/what-we-do/resource-sector-complex-planning-analysis/':['Labour','Infrastructure','Logistics','Approvals','Capital','Schedule'],
 '/what-we-do/long-range-financial-scenario-planning/':['Base case','Assumptions','Scenario','Sensitivity','Trigger'],
 '/what-we-do/public-interest-research-evidence-packages/':['Claim','Source','Evidence status','Conflict or gap','Implication']};
export function CapabilityDetailTemplate({page}:{page:PublicPage}){return <><PageHero page={page} eyebrow={page.topic}/><main className="public-container capability-body"><section className="decision-split"><div><p className="section-label">The decision</p><Markdown source={section(page.source,'The consequential decision')||section(page.source,'The decision')} path={page.path}/></div><div className="condition-panel"><p className="section-label">What usually controls it</p><Markdown source={section(page.source,'The controlling condition')} path={page.path}/></div></section><section className="analysis-section"><div><p className="section-label">Analytical structure</p><h2>Make the controlling chain visible.</h2></div><ol className={`analysis-chain chain-${chains[page.path]?.length}`}>{chains[page.path].map((item,index)=><li key={item}><span>{String(index+1).padStart(2,'0')}</span><b>{item}</b><ArrowRight aria-hidden="true"/></li>)}</ol><div className="analysis-copy"><Markdown source={section(page.source,'The analysis')} path={page.path}/></div></section><section className="output-section"><div><p className="section-label">Usable output</p><h2>Leave behind something the decision-maker can use.</h2></div><div className="output-panel"><Check/><Markdown source={bodyWithoutHeading(section(page.source,'The usable output'))} path={page.path}/></div></section><section className="related-panel"><div><p className="section-label">Related insight</p><Markdown source={section(page.source,'Related thinking')} path={page.path}/></div><div className="related-work"><p className="section-label">Selected work</p><h2>Selected work</h2><Link className="text-link" to="/selected-work/">See selected work <ArrowRight/></Link></div></section></main><ContactBand/></>}

export function AboutTemplate({page}:{page:PublicPage}){return <><PageHero page={page} eyebrow="Who we are"/><main className="public-container prose-sections"><Markdown source={page.source.replace(intro(page.source),'')} path={page.path}/></main><ContactBand/></>}
export function InsightsHubTemplate({page}:{page:PublicPage}){const featured=children(section(page.source,'Featured')),more=children(section(page.source,'More from DDA'));return <><PageHero page={page} eyebrow="Insights"/><main className="public-container public-section"><div className="insights-hub-grid">{[...featured,...more].map((item,index)=><article className={index===0?'featured':''} key={item.title}><span className="card-index">0{index+1}</span><h2>{item.title}</h2><Markdown source={item.body} path={page.path}/></article>)}</div><section className="insight-method"><Markdown source={section(page.source,'How our thinking supports the work')} path={page.path}/></section></main><ContactBand/></>}
export function InsightArticleTemplate({page}:{page:PublicPage}){const content=page.source.replace(/^# .+\n+/,'');return <><article className="article-template"><header><div className="public-container"><Crumb page={page}/><p className="section-label">DDA insight · {page.topic}</p><h1>{page.title}</h1></div></header><div className="article-layout public-container"><aside><span>In this analysis</span>{[...page.source.matchAll(/^## (.+)$/gm)].slice(0,5).map(m=><a key={m[1]} href={`#${m[1].toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{m[1]}</a>)}</aside><div className="article-copy"><Markdown source={content} path={page.path}/></div></div></article><ContactBand/></>}
export function SelectedWorkTemplate({page}:{page:PublicPage}){const stories=page.source.split(/^## /m).slice(2,-1).map(part=>{const [title,...body]=part.trim().split('\n');return {title,body:body.join('\n')}});return <><PageHero page={page} eyebrow="Selected work"/><main className="work-stories public-container">{stories.map((story,index)=><article key={story.title}><div className="work-number">{String(index+1).padStart(2,'0')}<span>Decision instrument</span></div><div><h2>{story.title}</h2><Markdown source={story.body} path={page.path}/></div></article>)}</main><ContactBand/></>}
export function ContactTemplate({page}:{page:PublicPage}){return <><PageHero page={page} eyebrow="Contact" showCta={false}/><main className="contact-template public-container"><div className="contact-aside"><p className="section-label">A useful first message</p><h2>Decision. Deadline. Consequence. Material.</h2><p>You do not need a finished scope. Start with the choice that has to move.</p></div><ContactForm/></main></>}
export function UtilityTemplate({page}:{page:PublicPage}){return <><PageHero page={page} eyebrow="Information" showCta={false}/><main className="utility-template public-container"><Markdown source={page.source.replace(intro(page.source),'')} path={page.path}/></main></>}
