import { lazy, Suspense, useEffect } from 'react';
import { BrowserRouter, Navigate, Route, Routes, useLocation } from 'react-router-dom';
import Layout from './components/Layout'; import WebsitePage from './pages/WebsitePage'; import { AccessProvider } from './contexts/AccessContext'; import { pageByRoute,pages,routeAliases } from './content/siteContent';
const Tools=lazy(()=>import('./pages/DiagnosticsPage'));const WorkSafe=lazy(()=>import('./pages/WorkSafeBCDiagnosticPage'));const PST=lazy(()=>import('./pages/PSTDiagnostic'));const BCPST=lazy(()=>import('./pages/BCPSTDiagnosticPage'));const Province=lazy(()=>import('./pages/tools/ProvinceComparatorPage'));const Experience=lazy(()=>import('./pages/tools/ExperienceRatingOptimizerPage'));const Suppression=lazy(()=>import('./pages/tools/SuppressionAuditPage'));const Mental=lazy(()=>import('./pages/tools/MentalHealthForecasterPage'));const Surplus=lazy(()=>import('./pages/tools/SurplusAlertPage'));const Decarb=lazy(()=>import('./pages/tools/BCDecarbonizationModelPage'));const Executive=lazy(()=>import('./pages/tools/ExecutiveRiskBriefPage'));const Model=lazy(()=>import('./pages/model'));const NotFound=lazy(()=>import('./pages/NotFoundPage'));
function Head(){const {pathname}=useLocation();useEffect(()=>{const key=pathname==='/'?'/':pathname.endsWith('/')?pathname:pathname+'/';const page=pageByRoute[key];const title=page?.title||'DDA';const description=page?.description||'Strategic analysis and decision design for complex public and regulated systems.';document.title=`${title} — DDA`;const set=(selector:string,attribute:string,value:string,tag='meta')=>{let element=document.head.querySelector(selector);if(!element){element=document.createElement(tag);document.head.append(element)}element.setAttribute(attribute,value)};set('meta[name="description"]','content',description);set('meta[property="og:title"]','content',`${title} — DDA`);set('meta[property="og:description"]','content',description);set('meta[property="og:url"]','content',`https://ddanalytics.ca${key}`);set('meta[property="og:type"]','content',page?.type==='article'?'article':'website');set('link[rel="canonical"]','href',`https://ddanalytics.ca${key}`,'link');},[pathname]);return null}
const tools=[['tools/worksafe-repricing',WorkSafe],['tools/pst-diagnostic',PST],['tools/bc-pst-impact',BCPST],['tools/province-comparator',Province],['tools/experience-rating',Experience],['tools/suppression-audit',Suppression],['tools/mental-health-forecaster',Mental],['tools/surplus-alert',Surplus],['tools/bc-decarbonization',Decarb],['tools/executive-risk-brief',Executive]] as const;
const diagnosticAliases:Record<string,string>={'/diagnostics/pst-diagnostic':'/tools/pst-diagnostic','/diagnostics/worksafe-repricing':'/tools/worksafe-repricing','/diagnostics/province-comparator':'/tools/province-comparator','/diagnostics/experience-rating':'/tools/experience-rating','/diagnostics/suppression-audit':'/tools/suppression-audit','/diagnostics/mental-health-forecaster':'/tools/mental-health-forecaster','/diagnostics/surplus-alert':'/tools/surplus-alert','/diagnostics/bc-decarbonization-model':'/tools/bc-decarbonization','/diagnostics/executive-risk-brief':'/tools/executive-risk-brief','/worksafebc-repricing-risk-diagnostic':'/tools/worksafe-repricing','/bc-pst-impact-diagnostic':'/tools/bc-pst-impact'};
function DiagnosticRedirect(){const {pathname}=useLocation();const demo=pathname.replace('/diagnostics/demo/','/tools/').replace('bc-decarbonization-model','bc-decarbonization');return <Navigate replace to={diagnosticAliases[pathname]??(pathname.startsWith('/diagnostics/demo/')?demo:'/tools')}/>}
export default function App(){return <BrowserRouter><AccessProvider><Head/><Suspense fallback={<div className="loading">Loading…</div>}><Routes><Route element={<Layout/>}>{Object.keys(pages).map(path=><Route key={path} path={path} element={<WebsitePage/>}/>)}{Object.entries(routeAliases).map(([from,to])=><Route key={from} path={from} element={<Navigate replace to={to}/>}/>) }<Route path="tools" element={<Tools/>}/>{tools.map(([p,C])=><Route key={p} path={p} element={<C/>}/>)}<Route path="tools/experience-rating-optimizer" element={<Navigate replace to="/tools/experience-rating"/>}/><Route path="tools/bc-decarbonization-model" element={<Navigate replace to="/tools/bc-decarbonization"/>}/><Route path="work" element={<Navigate replace to="/selected-work/"/>}/><Route path="published" element={<Navigate replace to="/insights/"/>}/><Route path="method" element={<Navigate replace to="/who-we-are/"/>}/><Route path="diagnostics/*" element={<DiagnosticRedirect/>}/><Route path="worksafebc-repricing-risk-diagnostic" element={<DiagnosticRedirect/>}/><Route path="bc-pst-impact-diagnostic" element={<DiagnosticRedirect/>}/><Route path="*" element={<NotFound/>}/></Route><Route path="model/*" element={<Model/>}/></Routes></Suspense></AccessProvider></BrowserRouter>}
